import type { Metadata } from 'next';
import Link from 'next/link';
export const metadata: Metadata = { title: 'Свой порядок дня', alternates: { canonical: 'https://os.lattelix.ru/' } };
export default function AboutPage() {
  return <>
    <section className="site-hero">
      <div className="site-hero-copy"><p className="site-eyebrow"><span className="site-dot"/>Личное пространство · ранняя версия</p><h1>Меньше решений.<br/><span>Больше ясности.</span></h1><p className="site-lead">Протоколы, заметки и календарь — рядом. Чтобы видеть главное, сохранять мысли и возвращаться к тому, что действительно важно.</p><div className="site-actions"><Link className="site-button" href="/os">Открыть Personal OS <span aria-hidden="true">↗</span></Link><a className="site-text-link" href="#how">Посмотреть, как устроено <span aria-hidden="true">↓</span></a></div><p className="site-caption">Сейчас — вход владельца. Публичной регистрации пока нет.</p></div>
      <div className="site-preview" aria-label="Иллюстрация интерфейса, не личные данные"><div className="site-preview-top"><span className="site-preview-dots" aria-hidden="true">● ● ●</span><span>ТВОЁ ПРОСТРАНСТВО</span><span className="site-tag">Пример</span></div><div className="site-preview-body"><div className="site-preview-nav"><span className="active">Today</span><span>Capture</span><span>Review</span></div><p className="site-eyebrow">Сначала — главное</p><h2>Хороший день.<br/>В своём темпе.</h2><div className="site-preview-goal"><span>TOP 1</span><strong>Закончить один важный шаг</strong><p>Не весь проект. Понятный результат на сегодня.</p></div><div className="site-preview-metrics"><div><span>Режим дня</span><strong>Reduced</strong></div><div><span>Энергия</span><strong>3 <small>/ 5</small></strong></div><div><span>Основа</span><strong>Твой протокол</strong></div></div><div className="site-preview-note"><span aria-hidden="true">↳</span><p>Новая мысль? В Capture.<br/><small>Не держи всё в голове.</small></p></div></div><div className="site-preview-bottom">Условные данные для знакомства с проектом</div></div>
    </section>
    <section className="site-section" id="how"><div className="site-section-heading"><p className="site-eyebrow">Один простой цикл</p><h2>Начать. Зафиксировать.<br/>Оглянуться.</h2><p>Не ещё одно место, которое нужно обслуживать. Три входа в одну систему.</p></div><div className="site-features"><article><span className="site-number">01 / TODAY</span><h3>Собери сегодняшний день</h3><p>Выбери режим, отметь энергию, запиши один главный результат. Открой дневную заметку и ближайшие события.</p></article><article><span className="site-number">02 / CAPTURE</span><h3>Освободи голову</h3><p>Сохрани мысль, задачу или наблюдение в Inbox своего Obsidian. Без необходимости сразу выбирать правильную папку.</p></article><article><span className="site-number">03 / REVIEW</span><h3>Увидь, что получилось</h3><p>Вернись к прошлым Daily, посмотри на факты и реши, что оставить, а что изменить в своём протоколе.</p></article></div></section>
    <section className="site-section site-connections"><div><p className="site-eyebrow">Свои данные. Знакомые инструменты.</p><h2>Не переносить жизнь.<br/>Соединить нужное.</h2><p className="site-lead">LifeDeck — интерфейс поверх твоих источников, а не повод отказаться от них.</p></div><div className="site-connection-list"><article><span className="site-service">Obsidian + GitHub</span><h3>Заметки остаются заметками</h3><p>Чтение протоколов, Daily и выбранного контекста. Сохранение Capture и изменений обратно в приватный репозиторий Markdown.</p></article><article><span className="site-service">Google Calendar · по разрешению</span><h3>Календарь рядом с планом</h3><p>Ближайшие события выбранных календарей и создание новых блоков по твоему действию. Доступ нужен для отображения названий, описаний, времени и идентификаторов событий.</p><p>Рекомендуемое разрешение — <code>calendar.events.owned</code>. Оно шире текущего интерфейса: Google разрешает также изменение и удаление событий, но эта версия LifeDeck только читает и создаёт их. Gmail и Google Drive не подключаются.</p><Link href="/privacy#google">Как используются данные Google ↗</Link></article></div></section>
    <section className="site-principles"><p className="site-eyebrow">Приватное — по умолчанию</p><h2>Публичен проект.<br/>Не твоя повседневность.</h2><p>Лендинг и документы открыты. Протоколы, календарь и записи доступны только после входа владельца. Они не включаются в публичный профиль активности.</p><div className="site-actions"><Link className="site-text-link" href="/privacy">Политика конфиденциальности ↗</Link><a className="site-text-link" href="https://github.com/lattelix/lifedeck" target="_blank" rel="noreferrer">Код проекта на GitHub ↗</a></div></section>
    <section className="site-section site-status"><div><p className="site-eyebrow">Честно о текущей версии</p><h2>Полезная основа.<br/>Не автопилот.</h2></div><div><p>Уже есть личный вход, Today, протоколы, Capture, просмотр истории и серверные подключения к Obsidian и Google Calendar. Коннекторы нужно настроить отдельно.</p><p>Автоматическая пересборка дня, голосовой разбор, почта и аккаунты для каждого пользователя — дальнейшее развитие, не обещание работающих функций. Приложение не гарантирует продуктивность и не заменяет медицинскую помощь.</p><Link className="site-button" href="/os">Перейти к своему пространству ↗</Link></div></section>
  </>;
}
